In [22]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [23]:
df = pd.read_csv(r"C:\Users\kanik\Downloads\train.txt.zip", sep = ';', header = None, names = ['text', 'emotions'])

In [24]:
df

                                                    text emotions
0                                i didnt feel humiliated  sadness
1      i can go from feeling so hopeless to so damned...  sadness
2       im grabbing a minute to post i feel greedy wrong    anger
3      i am ever feeling nostalgic about the fireplac...     love
4                                   i am feeling grouchy    anger
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...  sadness
15996  i am now turning and i feel pathetic that i am...  sadness
15997                     i feel strong and good overall      joy
15998  i feel like this was such a rude comment and i...    anger
15999  i know a lot but i feel so stupid because i ca...  sadness

[16000 rows x 2 columns]

In [25]:
df.isna().sum()

text        0
emotions    0
dtype: int64

#  Handling Output Labels (Target Encoding)

In [28]:
unique_emotions = df['emotions'].unique()

In [32]:
emotions_num = {}

In [33]:
i = 0
for e in unique_emotions:
    emotions_num[e] = i
    i=+1
df['emotions'] = df['emotions'].map(emotions_num)

In [34]:
df

                                                    text  emotions
0                                i didnt feel humiliated         0
1      i can go from feeling so hopeless to so damned...         0
2       im grabbing a minute to post i feel greedy wrong         1
3      i am ever feeling nostalgic about the fireplac...         1
4                                   i am feeling grouchy         1
...                                                  ...       ...
15995  i just had a very brief time in the beanbag an...         0
15996  i am now turning and i feel pathetic that i am...         0
15997                     i feel strong and good overall         1
15998  i feel like this was such a rude comment and i...         1
15999  i know a lot but i feel so stupid because i ca...         0

[16000 rows x 2 columns]

#  Lowercasing

In [39]:
df['text'] = df['text'].str.lower()   # df['text'] = df['text'].apply(lambda x : x.lower())

# Removing Punctuation

In [40]:
import string

def remove_punch(txt):
    return txt.translate(str.maketrans('','',string.punctuation))

In [41]:
df['text'] = df['text'].apply(remove_punch)

In [42]:
df

                                                    text  emotions
0                                i didnt feel humiliated         0
1      i can go from feeling so hopeless to so damned...         0
2       im grabbing a minute to post i feel greedy wrong         1
3      i am ever feeling nostalgic about the fireplac...         1
4                                   i am feeling grouchy         1
...                                                  ...       ...
15995  i just had a very brief time in the beanbag an...         0
15996  i am now turning and i feel pathetic that i am...         0
15997                     i feel strong and good overall         1
15998  i feel like this was such a rude comment and i...         1
15999  i know a lot but i feel so stupid because i ca...         0

[16000 rows x 2 columns]

# Removing Numbers from text

In [43]:
def remove_numbers(txt):
    new = ""
    for i in txt:
        if not i.isdigit():
            new = new + i
    return new

df['text'] = df['text'].apply(remove_numbers)

# Remove URLs/Links

# Remove HTML tags

# Remove Emojies

In [44]:
def remove_emojis(txt):
    new = ""
    for i in txt:
        if i.isascii():
            new += i
    return new

df['text'] = df['text'].apply(remove_emojis)

# Removing Stopwords